[package]
edition = "2018"
name = "nuid"
version = "0.2.1"
authors = ["Ivan Porto Carrero <ivan@oflanders.co.nz>"]
license = "Apache-2.0"
repository = "https://github.com/casualjim/rs-nuid.git"
readme = "README.md"
keywords = ["nuid","guid","uuid"]
description = "A highly performant unique identifier generator."

[dependencies]
lazy_static = "^1.2"
rand = "^0.7"
